pipeline {
  agent any
    
    stages {
        stage('Build') {
            steps {
		           sh 'primary'
		           sh 'docker build -t vanashree/mployee:""$BUILD_ID"" .'
	       }
        }
        stage('Publish') {
            steps {
                withDockerRegistry([credentialsID:"dockerhub_id",url:""]){
                    sh 'docker push vanashree/mployee:""$BUILD_ID"" '
                }
            }
        }
	
    }
}