pipeline {
    agent any
    
    environment {
        dockerImage= ''
        registry='vanashree/employee'
        registryCredential='dockerhub_id'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/VanashreeP/EMS.git']]])
            }
        }
        stage('Build Docker image') {
            steps {
                script {
                    dockerImage=docker.build registry
                }
            }
        }
	stage('Uploading image') {
            steps {
                script {
                    docker.withRegistry('',registryCredential) {
                        dockerImage.push();
                    }
                }
            }
        }
    }
}